"""initial migration

Revision ID: c22b5622c2cd
Revises: 
Create Date: 2019-05-20 15:38:15.346834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c22b5622c2cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('roles_id_uindex', table_name='roles')
    op.create_unique_constraint(None, 'roles', ['name'])
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'email_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_address', mysql.VARCHAR(length=30), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_index('roles_id_uindex', 'roles', ['id'], unique=True)
    # ### end Alembic commands ###
